#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width        0
bspc config window_gap          3

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#feh --bg-fill /home/viggo/Desktop/wallpapers/waves/Waves\ Dark\ Alt\ 6016x6016.jpg
feh --bg-fill ~/.config/wallpaper/nl.jpg
xrandr --output HDMI-0 --mode 1920x1080 --rate 144.01

bash ~/.config/polybar/launch.sh --config=~/dotfiles/.config/config bar1
picom --experimental-backends --backend glx --xrender-sync-fence

xsetroot -cursor_name left_ptr &
wmname LG3D
